# Upper versions display problems on buid/deploy
runtime: nodejs10


# Change file extensiones & redirects to index.html
handlers:
- url: /(.*\..+)$ 
  static_files: dist/\1
  upload: dist/(.*\..+)$
- url: /.*
  static_files: dist/index.html
  upload: dist/index.html